#!/usr/bin/env python3

import json
import sys


items = sorted(json.load(sys.stdin), key=lambda item: item.get("title", "").lower())
print("# Generated by chezmoi from 1Password SSH Key items.")
print("# Schema:")
print("#   - URL field: ssh://user@host")
print("#   - optional hostname field: actual target host/IP when different from the SSH alias")
print("#   - optional port field")
print("# Do not edit manually.")
print()

for item in items:
    fields = {f.get("label"): f.get("value") for f in item.get("fields", [])}
    url = next(
        (
            f.get("value")
            for f in item.get("fields", [])
            if f.get("type") == "URL" and isinstance(f.get("value"), str) and f.get("value", "").startswith("ssh://")
        ),
        None,
    )
    if not url:
        continue

    rest = url.removeprefix("ssh://")
    if "@" in rest:
        url_user, url_host = rest.split("@", 1)
    else:
        url_user, url_host = None, rest

    host = url_host
    hostname = fields.get("hostname")
    user = fields.get("user") or url_user
    port = fields.get("port")
    fingerprint = fields.get("fingerprint")

    if not (host and user and fingerprint):
        continue

    identity_file = fingerprint.replace(":", "_").replace("/", "_")

    print(f"# 1Password Item: {item['title']}")
    print(f"Host {host}")
    if hostname:
        print(f"    HostName {hostname}")
    print(f"    User {user}")
    print("    IdentitiesOnly yes")
    print(f"    IdentityFile ~/.ssh/1Password/{identity_file}.pub")
    if port:
        print(f"    Port {port}")
    print()
