tap "common-fate/granted"
tap "FelixKratz/formulae"
tap "hashicorp/tap"
tap "mongodb/brew"
tap "shivammathur/extensions"
tap "shivammathur/php"
tap "go-task/tap"

brew "atuin" # Improved shell history for zsh, bash, fish and nushell
brew "bash" # Bourne-Again SHell, a UNIX command interpreter
brew "awscli" # Official Amazon AWS command-line interface
brew "cookiecutter" # Utility that creates projects from templates
brew "borders" # A window border system for macOS
brew "cosign" # Container Signing (needed for tenv)
brew "gh" # GitHub command-line tool
brew "go-task/tap/go-task" # Task is a task runner/build tool that aims to be simpler and easier to use
brew "git" # Distributed revision control system
brew "gnupg" # GNU Pretty Good Privacy (PGP) package
brew "granted" # The easiest way to access your cloud.
brew "jq" # Lightweight and flexible command-line JSON processor
brew "make" # Utility for directing compilation
brew "mas" # Mac App Store command-line interface
brew "mongodb-database-tools" # Standard utilities for interacting with MongoDB.
brew "neovim" # Ambitious Vim-fork focused on extensibility and agility
brew "hashicorp/tap/packer" # https://www.packer.io/
brew "pinentry-mac" # Pinentry for GPG on Mac
brew "ripgrep" # Search tool like grep and The Silver Searcher
brew "starship" # Cross-shell prompt for astronauts
brew "tenv" # OpenTofu / Terraform / Terragrunt / Atmos version manager
brew "tmux" # Terminal multiplexer
brew "wget" # Internet file retriever

### PHP

brew "shivammathur/php/php@8.3" # General-purpose scripting language
brew "shivammathur/extensions/amqp@8.3" # AMQP PHP extension
brew "shivammathur/extensions/apcu@8.3" # APCU PHP extension
brew "shivammathur/extensions/grpc@8.3" # gRPC PHP extension
brew "shivammathur/extensions/igbinary@8.3" # IGBinary PHP extension
brew "shivammathur/extensions/mongodb@8.3" # MongoDB PHP extension
brew "shivammathur/extensions/msgpack@8.3" # MSGPack PHP extension
brew "shivammathur/extensions/protobuf@8.3" # Protobuf PHP extension
brew "shivammathur/extensions/redis@8.3" # Redis PHP extension
brew "shivammathur/extensions/xdebug@8.3" # XDebug PHP extension

### Fonts

cask "font-fira-code-nerd-font" # FiraCode Nerd Font (Fira Code)

### Casks

cask "1password" # Password manager that keeps all passwords secure behind one password
cask "1password-cli" # Command-line interface for 1Password
cask "aws-vault" # Securely store and access AWS credentials in development environments
cask "cardhop" # Contacts manager
cask "discord" # Voice and text chat software
cask "droplr" # Screenshot and screen recorder
cask "duckduckgo" # Web browser focusing on privacy
cask "fantastical" # Calendar software
cask "ghostty" # Terminal emulator that uses platform-native UI and GPU acceleration
cask "jetbrains-toolbox" # JetBrains tools manager
cask "karabiner-elements" # Keyboard customizer
cask "logi-options-plus" # Software for Logitech devices
cask "mailmate" # IMAP email client
cask "microsoft-excel" # Spreadsheet software
cask "microsoft-word" # Word processor
cask "mongodb-compass" # Interactive tool for analyzing MongoDB data
cask "obsidian" # Knowledge base that works on top of a local folder of plain text Markdown files
cask "orbstack" # Replacement for Docker Desktop
cask "orion" # WebKit based web browser
cask "prismlauncher" # PHP Monitor
cask "rapidapi" # HTTP client that helps testing and describing APIs
cask "raycast" # Control your tools with a few keystrokes
cask "signal" # Instant messaging application focusing on security
cask "slack" # Team communication and collaboration software
cask "spotify" # Music streaming service
cask "sublime-merge" # Git client
cask "sublime-text" # Text editor for code, markup and prose
cask "tailscale" # Mesh VPN based on WireGuard
cask "telegram" # Messaging app with a focus on speed and security
cask "whatsapp" # Native desktop client for WhatsApp
cask "zen-browser" # Gecko based web browser

### MAS

mas "1Password for Safari", id: 1569813296
mas "iBar Pro", id: 6737150304
mas "Kagi Search", id: 1622835804
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Patterns", id: 429449079
