"$schema" = 'https://starship.rs/config-schema.json'

[direnv]
disabled = false

[gcloud]
disabled = true

[kubernetes]
disabled = false

[status]
disabled = false

[package]
disabled = true

[gradle]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[nodejs]
disabled = true
